### PR TITLE
function to pull from local storage, also updated .gitignore for mac …

### PR DESCRIPTION
**Pull request by paulzimmclay**
check it out (see last column)

### CODE REVIEW

**Comment by AnEvilHerbivore** [comment]
Recommend you add in logic to test if the database exists, and if it doesn't, create an empty array to return.

**Comment by paulzimmclay** [comment]
figuring out how to test this

**Comment by paulzimmclay** [comment]
```
git fetch --all
git checkout localStorageRetrieval
```
see two functions added as methods on manageDB.js
see empty array "tasks" added to local storage

**Comment by joshdbarton** [comment]
:guinea: :pig:

**Pull request merged**
